zookeeper:
  image: wurstmeister/zookeeper
  ports: ["2181", "2888", "3888"]

kafka:
  build: kafka
  ports: ["9092"]
  links:
    - zookeeper:zk
  environment:
    HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    # Replace this env var if the HOSTNAME_COMMAND doesn't work.
    # This is required for certain docker runtimes like Docker for
    # Mac since the bridge IP isn't available on the host. Note that
    # localhost / 127.0.0.1 will NOT work here.
    # KAFKA_ADVERTISED_HOST_NAME: [your host interface]
    KAFKA_CREATE_TOPICS: "topicA:1:1,topicB:3:3,topicC:8:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

zk-web:
  image: tobilg/zookeeper-webui
  ports: ["9000:9000"]
  links:
    - zookeeper:zk
  environment:
    HTTP_PORT: 9000
    ZK_DEFAULT_NODE: zk:2181