// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("kafunk")>]
[<assembly: AssemblyProductAttribute("kafunk")>]
[<assembly: AssemblyDescriptionAttribute("F# client for Kafka")>]
[<assembly: AssemblyVersionAttribute("0.1.12")>]
[<assembly: AssemblyFileVersionAttribute("0.1.12")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "kafunk"
    let [<Literal>] AssemblyProduct = "kafunk"
    let [<Literal>] AssemblyDescription = "F# client for Kafka"
    let [<Literal>] AssemblyVersion = "0.1.12"
    let [<Literal>] AssemblyFileVersion = "0.1.12"
